### ISSUE TITLE
In the setting of koop ckan

### ISSUE THREAD

**Issue by ValueCreation** [Esri/koop#158]
Hello

https://github.com/koopjs/koop-sample-app
Installing to the Amazon Linux environment.

In the setting of koop ckan,
Register CKAN Hosts
curl --data "host = https: //catalog.data.gov&id=datagov" localhost: 1337 / ckan

You will see an error such as the following.
I would do anything to understand.

TypeError: undefined is not a function
    at Object.module.exports.serviceRegister (/var/www/html/koop-sample-app/node_modules/koop/lib/Local.js:55:5)
    at /var/www/html/koop-sample-app/node_modules/koop-ckan/models/ckan.js:15:21
    at Object.module.exports.serviceCount (/var/www/html/koop-sample-app/node_modules/koop/lib/Local.js:59:5)
    at Object.ckan.register (/var/www/html/koop-sample-app/node_modules/koop-ckan/models/ckan.js:13:19)
    at controller.register (/var/www/html/koop-sample-app/node_modules/koop-ckan/controller/index.js:22:12)
    at Layer.handle [as handle_request] (/var/www/html/koop-sample-app/node_modules/express/lib/router/layer.js:82:5)
    at next (/var/www/html/koop-sample-app/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/var/www/html/koop-sample-app/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/var/www/html/koop-sample-app/node_modules/express/lib/router/layer.js:82:5)
    at /var/www/html/koop-sample-app/node_modules/express/lib/router/index.js:267:22

**Comment by chelm** [comment]
This looks like its an issue with the Local Cache in lib/Local.js. I take a peek and see. Locally I run koop with PostGIS as the Cache and the ckan service registration works well there, but I'll try to get a fix for this into the next release of koop (today).

**Comment by chelm** [comment]
@ValueCreation This specific issue is resolved in the latest version of Koop v2.1.5 - Though I had some trouble accessing the CKAN api for data.gov. I have had more luck getting the CKAN provider to work with http://www.civicdata.com than data.gov

**Comment by ValueCreation** [comment]
Thanks you
I was able to confirm.
