### ISSUE TITLE
Japanese Data Catalog site

### ISSUE THREAD

**Issue by ValueCreation** [Esri/koop#160]
Japanese Data Catalog site the following error message where it was registered was displayed.

It is this would be difficult feeling.
We will take a look at the source files myself.

http://www.data.go.jp

curl --data "host=http://www.data.go.jp&id=datagojp" localhost:1337/ckan

/ckan/datajp undefined {} {}

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/var/www/html/koop-sample-app/node_modules/koop-ckan/models/ckan.js:49:23)
    at Request.self.callback (/var/www/html/koop-sample-app/node_modules/koop-ckan/node_modules/request/request.js:368:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/html/koop-sample-app/node_modules/koop-ckan/node_modules/request/request.js:1219:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/www/html/koop-sample-app/node_modules/koop-ckan/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
[kamiya@ip-172-31-17-145 koop-sample-app]$

**Comment by chelm** [comment]
@ValueCreation yes this is the same thing I see when I try to use data.gov in Koop. It has to do with the CKAN api not returning what koop expects. The endpoint on CKAN is `/api/3/action/package_list` and seems to not always work.

**Comment by ValueCreation** [comment]
Are you see. Is OK.
Thanks you.
